### ISSUE TITLE
Metadata added by user are lost after submission

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/chemotion_REPO#107]
Hi Team,

after uploading an analysis in Chemotion ELN and adding Metadata to it, I started the transfer to Chemotion Repo.
In Repo (ELN Gate) I checked and finished everything and started the submission for publication.
During this process and after looking at the sample for reviewing, all Metadata I added manually are lost:
![grafik](https://github.com/user-attachments/assets/4497e819-ede1-4672-8f77-3b766edf20cf)
https://chemotion-repository.net/home/review/review_sample/118952 
Only the ones coming from the device / file / converter are still there.
The Repo also seems to creates a double of the Bagit File during submission.

#### Summary:

1. Creating Analysis in ELN, upload a File and adding manual Metadata to it (shared with IT-hd as DHM-22).
2. Assign the sample to "chemotion-repo"-Collection and click on the cloud icon to transfer it (Metadata still complete)
3. In Repo ELN-Gate finish everything and click on the paper plane to start the review process (Metadata still complete in ELN Gate)
4. Look at the sample at the "Pending Publications"-Collection or the Review Page as Review Account: Manual added Metadata are lost and a second Bagit-File is created

#### Video showing the whole process:
https://drive.google.com/file/d/12LyogRqsn95Ys3xLE1_NbMxUR2xsc7uG/view?usp=sharing 

I tested the workflow with Gamry CV, NOVA CV and 1H NMR data.
Also, it does not matter if using the Complat ELN nor the ELN from Aachen.

Thanks for your help in advances.

**Comment by alhoch** [comment]
I can confirm this behaviour

**Comment by cllde8** [comment]
This issue has been resolved.
