### ISSUE TITLE
Strange user experience when opening analyses 

### ISSUE THREAD

**Issue by robertgiessmann** [ComPlat/chemotion_REPO#11]
Hi there!

I was clicking around the chemotion repository at https://www.chemotion-repository.net/ and went for [home/publications/reactions/6356](https://www.chemotion-repository.net/home/publications/reactions/6356) -- there I opened Analyses -> 1H NMR -> Datasets -> 1H (clicking on a blue "1H"). Then comes this screen:

![Screenshot 2022-02-18 at 14 31 41](https://user-images.githubusercontent.com/57750026/154692324-114ebe17-accf-46a4-8ec9-214e8ebc7c25.png)

It feels strange to me that I have to click "Discard" and can't click "Close".

Just wanted to let you know!

Best,
   Robert

**Comment by baolanlequang** [comment]
@adambasha0 I was fixed on the current version.

**Comment by phuang26** [comment]
The UI has been updated; only one button for closing the window.
