### ISSUE TITLE
comment function for reviewers and users

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_REPO#20]
The comment function for reviewers is realized via a modal that opens up for adding the comments. This modal can be moved from one place to another which is very good. But: the move function is enabled in a way that hinders to go to one specific text part to edit or copy it - because the system detects the action as indication to move the modal (instead of mark specific items in the text field). Can one enable the move action to be active only for specific parts of the modal?

**Comment by cllde8** [comment]
Hi @nicolejung

Thank you for your suggestion. The new implementation has been completed and released. Consequently, I am here to close this item.
