### ISSUE TITLE
publish sample: pre-chosen license

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_REPO#27]
Once the data of a sample is gathered, users of Chemotion Repository might click on the little paper aeroplane ![Chemotion_publish_sample_licence_button](https://user-images.githubusercontent.com/85482437/201661322-890457db-df91-4fb8-b088-85e9c1dabb01.PNG)
 to open the "Publish Sample" panel. 

![Chemotion_publish_sample_licence](https://user-images.githubusercontent.com/85482437/201660657-0b8b8019-ae91-4a2e-9687-8baa3daed006.PNG)

Pre-set license chosen by Chemotion Repository is CC BY-SA. There might be challenges in the re-use of research data if data under CC BY-SA is re-used together with research data under totally other licenses and CC BY-SA with (scientific) publications is often not considered as open-access compliant.

I would suggest to change the pre-set license to CC BY.

Best,
Tillmann

**Comment by nicolejung** [comment]
I support that as well

**Comment by cllde8** [comment]
Dear @tilfischer,

Thanks for your valuable contribution! Your suggestion has been implemented and released on Chemotion Repository. The preset license for samples/reactions has been updated to 'CC BY'. We appreciate your help in improving the platform.

Best regards,
Claire
