### ISSUE TITLE
directing issue related to login

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_REPO#38]
it would be great if the following directing issue could be corrected: 
- if a user is linked to a dataset in the repo (e.g. per DOI link) and is not logged in, the functions are reduced. 
- if the user wants to have full functionality, then he needs to log in
- log in leads to home, not to the required original entry,

**Comment by cllde8** [comment]
Dear @nicolejung,

Thank you for your valuable contribution! As per our discussion, these updates have been released on Chemotion Repository. Therefore, I am closing this ticket.

Best regards,
Claire
