### ISSUE TITLE
White Screen when clicking on Analysis DOI

### ISSUE THREAD

**Issue by ChrizzleGrazzl** [ComPlat/chemotion_REPO#42]
If you click on the DOI generated for a certain analysis only white screen is displayed.
See attached video:

https://github.com/ComPlat/chemotion_REPO/assets/126082604/c4a874a8-639a-4d30-89bf-8e6bf8f34d7d

**Comment by phuang26** [comment]
@ChrizzleGrazzl Thank you for reporting this issue. It has now been fixed, so please try again.
