### ISSUE TITLE
White Screen when checking Reviewers' comments

### ISSUE THREAD

**Issue by ChrizzleGrazzl** [ComPlat/chemotion_REPO#43]
Reviewers' comments cannot be checked due to a white screen after clicking on the respective button.
See in video:

https://github.com/ComPlat/chemotion_REPO/assets/126082604/e73bb3b2-5c61-4db8-97d1-491532281cc6

**Comment by phuang26** [comment]
@ChrizzleGrazzl  I apologize for the inconvenience. The issue has been resolved, and you can now reload the page and try again. Thank you for your patience.
