### ISSUE TITLE
published on and ISO8601

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_REPO#46]
Dear all,

we recently listened to a presentation where someone presented data in Chemotion Repository, but the presenter could not tell whether data was published on the 2nd June 2023 or 6th February 2023 (based on this example https://dx.doi.org/10.14272/QTFCYZQONWMAKG-UHFFFAOYSA-N.1) . While embargo uses ISO8601 and its main recommendation to use YYYY-MM-DD, the "Published on" field in Chemotion Repository uses DD-MM-YYYY, which, on the first sign, could be mixed up with MM/DD/YYYY (AE) or DD/MM/YYYY (BE) and is not ISO8601 compliant. 

I would suggest to change this to YYYY-MM-DD, as with the embargo, to avoid any further confusions.

Best

**Comment by cllde8** [comment]
Dear @tilfischer,

Thanks for your valuable contribution! Your suggestion has been implemented and released on Chemotion Repository. We appreciate your help in improving the platform.

Best regards,
Claire
