### ISSUE TITLE
Chemotion ELN Generic Dataset Designer cannot reach LabIMotion Hub (Chemotion Repository)

### ISSUE THREAD

**Issue by Thomas-Emmler-Hereon** [ComPlat/chemotion_REPO#62]
When I want to add new templates from Generic Dataset Designer to Chemotion ELN (version 1.8.1), no connection to the Chemotion repository can be established (ditto for Generic Segments Desiger & Generic Elements Designer).
Error message: "Cannot Connect to Chemotion Repository."

The page www.chemotion-repository.net can be accessed with the browser or (via curl) from the ELN container without any problems, so I think the problem probably lies outside of our network.

Best regards
...Thomas

**Comment by cllde8** [comment]
Hi @Thomas-Emmler-Hereon 

Thank you for bringing this issue to our attention. We conducted a migration yesterday and are currently looking into the network settings to address the reported concern.

Best regards,
Claire

**Comment by cllde8** [comment]
Hi @Thomas-Emmler-Hereon ,

The issue has been resolved. 

Best regards,
Claire

**Comment by Thomas-Emmler-Hereon** [comment]
Hi Claire (@cllde8 )
Thank you. This was really fast!
Best regards
...Thomas

**Comment by cllde8** [comment]
Hi Thomas (@Thomas-Emmler-Hereon )

You're welcome! I'm glad we could address the issue promptly. The matter will now be marked as closed.

Best regards,
Claire
