### ISSUE TITLE
[Documentation] REST API download_json undocumented

### ISSUE THREAD

**Issue by sneumann** [ComPlat/chemotion_REPO#67]
Hi, 
I couldn't find the documentation for a REST call like 
`https://www.chemotion-repository.net/api/v1/public/metadata/download_json?type=sample&id=968`

Since https://www.chemotion-repository.net/swagger_doc#/json-ld 
and the https://www.chemotion-repository.net/swagger_doc.json
do not mention `download_json` .

Nothing urgent, just wanted to mention. Yours, Steffen

**Comment by cllde8** [comment]
Hi @sneumann 

Thank you for bringing this to our attention. The [documentation](https://www.chemotion-repository.net/swagger_doc) has been updated accordingly. We truly appreciate your assistance in enhancing the platform.

Best regards,
Claire

**Comment by sneumann** [comment]
Wonderful, have a nice day! Yours, Steffen
