### ISSUE TITLE
ORCID Branding

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_REPO#76]
Dear all,

for anything connected to the organisation ORCID, please always have a look to https://info.orcid.org/brand-guidelines/ . In short: ORCID is an organisation and it is not an acronym anymore. Users may register and get an ORCID iD. Connected to this ORCID iD is an ORCID record. 

Non exhauste list: 

1) The sign up page asked for ORCID but actually means the ORCID iD: https://www.chemotion-repository.net/users/sign_up 

2) My Collaboration askes for ORCID, but the prefilled field suggests its the ORCID iD, which should be added but not the organisation.

3) https://www.chemotion-repository.net/pages/settings also lists ``orcid`` but not ORCID iD. 

This issue is of very low prio, but at some point that could be fixed. 

Best,
Tillmann

Edit: Added 3).

**Comment by cllde8** [comment]
Hi @tilfischer 

Thank you for bringing this to our attention. The issue has been resolved. Your help in improving the platform is greatly appreciated.

Best regards,
Claire

**Comment by tilfischer** [comment]
Thank you!

**Comment by tilfischer** [comment]
Checked this. All fine. Thank you again.
