### ISSUE TITLE
Add a warning before canceling an accound

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_REPO#78]
Dear all,

If a user is logged in, the user might change its password via https://www.chemotion-repository.net/users/edit . Below the prompt for the password is the red button to cancel the account. 

![Screenshot 2024-03-04 131020](https://github.com/ComPlat/chemotion_REPO/assets/85482437/e038e013-6a41-4baa-bab7-1b31ef16cd80)

Pressing the button, also accidentally, cancels the account, without any further warning. For me this seems quiet dangerous and I would suggest that the user some need to confirm the cancelation of his account.

Best,
Tillmann

**Comment by cllde8** [comment]
Hi @tilfischer,

Thank you for bringing this to our attention. The reported issue has been resolved.  You can find a video below for your reference. We appreciate your help in improving the platform.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.03.08-21_18_57.webm](https://github.com/ComPlat/chemotion_REPO/assets/42910431/466ef43e-db13-4fe8-bc56-a22bb74818ec)

Best regards,
Claire

**Comment by tilfischer** [comment]
Thank you!

**Comment by tilfischer** [comment]
Tested and confirmed.
