### ISSUE TITLE
File wasn't available on this site

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_REPO#96]
Dear all,

I went to https://dx.doi.org/10.14272/UVLHGRADYISRGZ-UHFFFAOYSA-N.11 and clicked on the dataset "ADO-1_CuTMGqu2PF6". On the pop up modal I tried to download a files, the browser asked me for a location to save these files but that gave an error: "File wasn't available on this site" (see screenshot). I repeated, and this gave the same error again.

![Screenshot (43)](https://github.com/ComPlat/chemotion_REPO/assets/85482437/20246e89-b74c-4650-88b0-fafacbbdfb47)

I then went to My DB for an unpublished sampled and successfully downloaded two files (see screenshot). Then, I went back to [Chemotion](https://dx.doi.org/10.14272/UVLHGRADYISRGZ-UHFFFAOYSA-N.11) and tried to download the file and other files again and I was able to download the files i.e. without any error.

However, this should work straight away. Any hints why this didn't initially worked? Possibly, this is an bug report.

Best,
Tillmann

**Comment by cllde8** [comment]
Dear @tilfischer,

Thank you for bringing this to our attention.

Users can download files via the buttons shown in the provided screenshot without the need to log in. 

![screenshot-www chemotion-repository net-2024 04 16-16_07_40](https://github.com/ComPlat/chemotion_REPO/assets/42910431/1002f084-100d-437f-8e8e-74932f79fc42)


This functionality has been implemented to facilitate convenient access to the data, and it's adapted from https://www.chemotion.net/docs/labimotion/guides/user/datasets/download?_highlight=metadata.

Please note that downloading files from the pop-up windows does require users to log in to the system first. This may explain why you were able to successfully download the file from the pop-up window after accessing My DB.

Best regards,
Claire

**Comment by tilfischer** [comment]
Dear Claire,

Thank you for this very prompt reply and the explanations provided. However, I have to say that it is not obvious that you need to log in first to download data via the pop-up modal. Could you explain why it is required to login before being able to download files via the pop up modal? For convenience, download should be allowed without login.

Best,
Tillmann

**Comment by cllde8** [comment]
Dear @tilfischer 

Yes, I agree. I don't see any reason to ask users to login before being able to download files via the pop up modal. It appears there may be an issue with controlling this function, and we will investigate further. Thank you once again for bringing it to our attention.

Best regards,
Claire

**Comment by tilfischer** [comment]
Thank you!

**Comment by cllde8** [comment]
Dear @tilfischer 

The issue has been resolved. Users can now download the file through the pop-up modal without requiring a login. We appreciate your help in improving the platform and thank you for your support.

Best regards,
Claire

**Comment by tilfischer** [comment]
Thank you!
